### ISSUE TITLE
Baixar XML pela chave do CFE

### ISSUE THREAD

**Issue by codingvs** [base4sistemas/satcfe#12]
Existe alguma forma de, através das bibliotecas disponibilizadas, baixar o arquivo XML a partir da chave do CFE / QR Code no CFE? Caso não exista, poderia informar a API adequada? Obrigado.

**Comment by danielgoncalves** [comment]
A SEFAZ/SP não desenvolveu nenhuma API/serviço para obtenção automatizada dos XML dos CF-e-SAT emitidos. Porém, para os CF-e-SAT que foram transmitidos do equipamento para a SEFAZ/SP, o contribuinte pode obter os XML a partir do [SGR-SAT](https://satsp.fazenda.sp.gov.br/COMSAT) (Sistema Gestão e Retaguarda do SAT).
