### ISSUE TITLE
sat urano (sat ur - desenvolvimento) 

### ISSUE THREAD

**Issue by denisdemais** [base4sistemas/satcfe#4]
boa tarde.
comecei o desenvolvimento com o SAT UR (urano) - devenvolvimento;

posso testar a app/api com ele.

**Comment by danielgoncalves** [comment]
Olá @denisdemais. 
Vá em frente e comente os resultados aqui ou na [nossa sala do Gitter](https://gitter.im/base4sistemas/satcfe) :wink:
