### ISSUE TITLE
Enable travis with flake8 and pylint

### ISSUE THREAD

**Issue by mileo** [base4sistemas/satcfe#6]
Posso fazer isso se quiserem!

**Comment by danielgoncalves** [comment]
Seria interessante, mas o projeto usa [Drone.io](https://drone.io/github.com/base4sistemas/satcfe/latest). Poderia introduzir flake8 e pylint e manter o Drone?

**Comment by mileo** [comment]
O Done não tem um arquivo de configuração similar ao travis?

**Comment by danielgoncalves** [comment]
Não tem. Há um hook do GitHub, quando tu consolida no ramo master ele dá o gancho no Drone.

**Comment by mileo** [comment]
Bom eu vou criar uma PR com os testes, vc poderia ativar o travis do repo?

**Comment by danielgoncalves** [comment]
Ativado. O build no Travis irá requerer o arquivo `.travis.yml`.

**Comment by mileo** [comment]
Obrigado
